workspace.dependencies.semver = ">=1.0.18"
workspace.dependencies.serde.features = ["derive"]
workspace.dependencies.serde.version = ">=1.0.187"
workspace.dependencies.tmr-cargo.path = "./packages/tmr-cargo"
workspace.dependencies.tmr-cargo-macros.version = "0.9.0"
workspace.dependencies.toml = ">=0.7.8"
workspace.dependencies.tracing = ">=0.1.37"
workspace.dependencies.tracing-subscriber.features = ["env-filter"]
workspace.dependencies.tracing-subscriber.version = ">=0.3.17"
workspace.exclude = ["target", "examples/workspace"]
workspace.members = ["packages/*", "examples/*", "target/tmr"]
workspace.package.authors = ["megumish <megumish@megumi.sh>"]
workspace.package.categories = ["cli", "automation", "macros"]
workspace.package.description = "Too many rust"
workspace.package.documentation = "https://github.com/megumish/tmr_cargo"
workspace.package.edition = "2021"
workspace.package.homepage = "https://github.com/megumish/tmr_cargo"
workspace.package.keywords = ["cli", "automation", "macros"]
workspace.package.license = "MIT"
workspace.package.publish = false
workspace.package.readme = "./README.md"
workspace.package.repository = "https://github.com/megumish/tmr_cargo.git"
workspace.package.rust-version = "1.72.0"
workspace.package.version = "0.9.2"
workspace.resolver = "2"
workspace.package.exclude = []
workspace.package.include = []
